import { AppError } from './errors';
import { isLocatorKind, type LocatorKind } from './enums';

/**
 * A reading position. `value` is the format-native anchor and `fraction` is a
 * normalized 0..1 fallback so progress remains comparable across formats and
 * screen sizes.
 */
export interface Locator {
  readonly kind: LocatorKind;
  readonly value: string;
  readonly fraction: number;
}

/**
 * CFI strings are deeply nested and generated by the reader engine, so this
 * layer only bounds their size rather than re-validating the grammar.
 */
export const MAX_LOCATOR_VALUE_LENGTH = 512;

export function clampFraction(value: number): number {
  if (!Number.isFinite(value)) return 0;
  if (value < 0) return 0;
  if (value > 1) return 1;
  return value;
}

export function isLocator(value: unknown): value is Locator {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return (
    isLocatorKind(candidate.kind) &&
    typeof candidate.value === 'string' &&
    candidate.value.length > 0 &&
    candidate.value.length <= MAX_LOCATOR_VALUE_LENGTH &&
    typeof candidate.fraction === 'number' &&
    Number.isFinite(candidate.fraction) &&
    candidate.fraction >= 0 &&
    candidate.fraction <= 1
  );
}

export function assertLocator(value: unknown): Locator {
  if (!isLocator(value)) {
    throw new AppError(
      'invalid_argument',
      'Invalid locator: expected a known kind, a non-empty value and a fraction within 0..1.',
    );
  }
  return value;
}

export function createCfiLocator(value: string, fraction: number): Locator {
  return assertLocator({ kind: 'cfi', value, fraction: clampFraction(fraction) });
}

/** PDF locators serialize as `<page>:<yOffset>` with a separate fraction. */
export function createPdfLocator(page: number, yOffset: number, fraction: number): Locator {
  if (!Number.isInteger(page) || page < 0) {
    throw new AppError('invalid_argument', 'PDF page must be a non-negative integer.');
  }
  if (!Number.isFinite(yOffset) || yOffset < 0) {
    throw new AppError(
      'invalid_argument',
      'PDF vertical offset must be a finite non-negative number.',
    );
  }
  return {
    kind: 'pdf',
    value: `${page}:${Math.round(yOffset)}`,
    fraction: clampFraction(fraction),
  };
}

export interface PdfPosition {
  readonly page: number;
  readonly yOffset: number;
}

export function parsePdfLocator(value: string): PdfPosition | null {
  // A value is `<page>:<yOffset>` and may carry extra `:`-separated fields
  // (a highlight adds `:<start>:<end>`); only the first two drive navigation.
  const parts = value.split(':');
  if (parts.length < 2) return null;
  const page = Number(parts[0]);
  const yOffset = Number(parts[1]);
  if (!Number.isInteger(page) || page < 0) return null;
  if (!Number.isFinite(yOffset) || yOffset < 0) return null;
  return { page, yOffset };
}

export interface PdfHighlightAnchor {
  readonly page: number;
  readonly yOffset: number;
  /** Character offsets into the page's rendered text layer. */
  readonly start: number;
  readonly end: number;
}

/**
 * A PDF highlight serializes as `<page>:<yOffset>:<start>:<end>`: the page and
 * scroll offset locate it for navigation, and the character range into the
 * page's text layer lets the renderer recompute the drawn rectangles at any
 * zoom. The kind stays `pdf` so no new locator kind (and no migration) is
 * needed.
 */
export function createPdfHighlightLocator(
  page: number,
  yOffset: number,
  start: number,
  end: number,
  fraction: number,
): Locator {
  if (!Number.isInteger(page) || page < 0) {
    throw new AppError('invalid_argument', 'PDF page must be a non-negative integer.');
  }
  if (!Number.isInteger(start) || !Number.isInteger(end) || start < 0 || end <= start) {
    throw new AppError('invalid_argument', 'PDF highlight range must be start < end, both >= 0.');
  }
  return {
    kind: 'pdf',
    value: `${page}:${Math.max(0, Math.round(yOffset))}:${start}:${end}`,
    fraction: clampFraction(fraction),
  };
}

export function parsePdfHighlight(value: string): PdfHighlightAnchor | null {
  const parts = value.split(':');
  if (parts.length < 4) return null;
  const page = Number(parts[0]);
  const yOffset = Number(parts[1]);
  const start = Number(parts[2]);
  const end = Number(parts[3]);
  if (![page, yOffset, start, end].every((n) => Number.isFinite(n))) return null;
  if (!Number.isInteger(page) || page < 0) return null;
  if (!Number.isInteger(start) || !Number.isInteger(end) || start < 0 || end <= start) return null;
  return { page, yOffset, start, end };
}

export function formatPercent(fraction: number): string {
  return `${Math.round(clampFraction(fraction) * 100)}%`;
}

/** Human-readable position summary used by library and detail views. */
export function describeLocator(locator: Locator | null): string {
  if (locator === null) return 'Not started';
  if (locator.kind === 'pdf') {
    const position = parsePdfLocator(locator.value);
    if (position) {
      return `Page ${position.page + 1} · ${formatPercent(locator.fraction)}`;
    }
  }
  return formatPercent(locator.fraction);
}
